steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/firebase/main:$TAG_NAME', '.' ]
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/firebase/main:$TAG_NAME'